In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print(X)

[[ -0.64047024 -15.66266192   3.81060842 ...  18.11349284  -3.32800744
    8.29926455]
 [  1.91852905  -0.90657936  -0.45334769 ...  -2.16963083   2.82681523
   -5.86774051]
 [ 15.9334402    2.16047452 -13.12843865 ...  -0.86623852   3.63612067
    9.27361905]
 ...
 [-10.609487   -14.86243608  -5.2927622  ... -10.37639733 -11.40732637
    6.37495591]
 [ -2.62155022  22.09545392   2.11914325 ...  -2.60237983   1.88615458
   -3.54557622]
 [  3.51193897   4.13093791   9.45947159 ...   4.71366864   6.81146008
  -13.86972915]]


In [3]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - mean) / std)
print(X_norm)

[[-0.11538514 -1.73395633  0.23892714 ...  1.67786278 -0.46114127
   0.6876089 ]
 [ 0.13817059 -0.24809212 -0.18456027 ... -0.35308452  0.13493739
  -0.73299134]
 [ 1.52682322  0.06074498 -1.44342441 ... -0.22257597  0.21331653
   0.78531256]
 ...
 [-1.10315461 -1.65337756 -0.66520103 ... -1.17482729 -1.24360242
   0.49464833]
 [-0.31167835  2.06809838  0.07093427 ... -0.39641564  0.04383683
  -0.50013569]
 [ 0.29605193  0.25916085  0.79996069 ...  0.33613962  0.52083993
  -1.5353929 ]]


In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [5]:
r = np.sum(Z, axis=1)
print(np.nonzero(r>10))

(array([1, 4, 5], dtype=int64),)


In [6]:
eye = np.eye(2)
print(eye)

[[1. 0.]
 [0. 1.]]


In [7]:
A = np.eye(3)
B = np.eye(3)
AB = np.vstack((A,B))

In [8]:
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
